
name: Daily Notion Job Bot

on:
  schedule:
    - cron: '0 14 * * *'  # Every day at 14:00 UTC (8 PM IST)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
